# Generated by Django 5.2.8 on 2025-11-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='marketplace',
            options={'managed': False},
        ),
    ]
