# Generated by Django 5.2.8 on 2025-12-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_alter_crop_options_alter_marketplace_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crop',
            table='crops',
        ),
        migrations.AlterModelTable(
            name='marketplace',
            table='marketplace',
        ),
    ]
