# Generated by Django 5.2.8 on 2026-01-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_alter_crop_options_alter_marketplace_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'managed': True},
        ),
        migrations.DeleteModel(
            name='Marketplace',
        ),
    ]
