# Generated by Django 5.2.8 on 2026-01-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_alter_crop_options_delete_marketplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('market_id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('predicted_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('farming_method', models.CharField(max_length=255)),
                ('farming_season', models.CharField(max_length=255)),
                ('additional_details', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('image', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Pending', 'Pending')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'managed': False},
        ),
    ]
