# Generated by Django 5.2.8 on 2026-01-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_marketplace_alter_crop_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crop',
            table='crops',
        ),
    ]
