# Generated by Django 5.2.8 on 2026-01-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_crop_alter_marketplace_options_favourite'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marketplace',
            table='market',
        ),
    ]
