# Generated by Django 5.2.8 on 2026-01-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_marketplace_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'managed': False},
        ),
    ]
