# Generated by Django 5.2.8 on 2026-01-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='chat',
        ),
    ]
