# Generated by Django 5.2.8 on 2025-12-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerdetails',
            old_name='phone',
            new_name='contact_number',
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
