# Generated by Django 5.2.8 on 2025-12-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_phone_farmerdetails_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerdetails',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='farmerdetails',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
