# Generated by Django 5.2.8 on 2025-12-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_full_name_buyerdetails_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdetails',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
