# Generated by Django 5.2.8 on 2025-12-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_farmerdetails_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdetails',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='buyer_msg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='harvest_rem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='market_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='price_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
