# Generated by Django 5.2.8 on 2025-12-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_farmerdetails_about_farmerdetails_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerdetails',
            name='address',
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='company_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='company_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='market_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='street_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
