# Generated by Django 5.2.8 on 2025-12-31 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_buyerdetails_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerdetails',
            old_name='street_address',
            new_name='address',
        ),
    ]
