# Generated by Django 5.2.8 on 2025-12-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_street_address_buyerdetails_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerdetails',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
