# Generated by Django 5.2.8 on 2025-12-31 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_buyerdetails_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerdetails',
            old_name='market_name',
            new_name='company_name',
        ),
    ]
