# Generated by Django 5.2.8 on 2026-01-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_market_name_buyerdetails_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerdetails',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
