# Generated by Django 5.2.8 on 2026-01-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_buyerdetails_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerdetails',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
