# Generated by Django 5.2.8 on 2026-01-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_buyerdetails_is_verified_buyerdetails_verified_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerdetails',
            old_name='verified_at',
            new_name='deactivate_at',
        ),
        migrations.RenameField(
            model_name='farmerdetails',
            old_name='verified_at',
            new_name='deactivate_at',
        ),
        migrations.RemoveField(
            model_name='buyerdetails',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='farmerdetails',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
