# Generated by Django 5.2.8 on 2026-03-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_activitylog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='accounts_ac_created_91b66e_idx',
            old_name='accounts_act_created_67706a_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='accounts_ac_action__d504cb_idx',
            old_name='accounts_act_action__186cc1_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='accounts_ac_module_98e67d_idx',
            old_name='accounts_act_module_95600c_idx',
        ),
    ]
