# Generated by Django 5.2.8 on 2026-01-24 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_remove_alert_calendar_added_remove_alert_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('SENT', 'Sent')], default='SENT', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(default='System Alert', max_length=150),
        ),
        migrations.AddField(
            model_name='alert',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('SUDDEN', 'Sudden'), ('SCHEDULED', 'Scheduled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='crop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserAlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_alert_id', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserAlert',
        ),
    ]
