# Generated by Django 5.2.8 on 2026-01-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_scheduled_for_alert_status_alert_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='level',
            field=models.CharField(choices=[('LOW', 'Low'), ('HIGH', 'High'), ('NORMAL', 'Normal')], default='NORMAL', max_length=10),
        ),
    ]
