# Generated by Django 5.2.8 on 2026-03-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='scheduled_for',
        ),
    ]
