# Generated by Django 4.2.16 on 2026-03-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_remove_alert_scheduled_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
