# Generated by Django 4.2.29 on 2026-03-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=50, unique=True)),
                ('model_version', models.CharField(max_length=20)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('training_samples', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.JSONField()),
                ('parameters', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Model Metadata',
            },
        ),
        migrations.CreateModel(
            name='TrendAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('metric', models.CharField(choices=[('PRICE', 'Price'), ('DEMAND', 'Demand'), ('YIELD', 'Yield')], max_length=10)),
                ('forecast_date', models.DateField()),
                ('predicted_value', models.FloatField()),
                ('baseline_value', models.FloatField(blank=True, null=True)),
                ('change_pct', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], max_length=10)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('NOTIFIED', 'Notified')], default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('yield', 'Yield Prediction'), ('price', 'Price Prediction'), ('demand', 'Demand Prediction')], max_length=20)),
                ('crop_name', models.CharField(max_length=100)),
                ('input_features', models.JSONField()),
                ('predicted_value', models.FloatField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prediction_type', 'crop_name'], name='ml_api_pred_predict_5bca99_idx'), models.Index(fields=['-created_at'], name='ml_api_pred_created_2e4ddc_idx')],
            },
        ),
    ]
