# Generated by Django 5.2.8 on 2026-02-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_id', models.IntegerField()),
                ('metric', models.CharField(choices=[('PRICE', 'Price'), ('DEMAND', 'Demand'), ('YIELD', 'Yield')], max_length=10)),
                ('forecast_date', models.DateField()),
                ('predicted_value', models.FloatField()),
                ('baseline_value', models.FloatField(blank=True, null=True)),
                ('change_pct', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], max_length=10)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('NOTIFIED', 'Notified'), ('IGNORED', 'Ignored')], default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('crop_id', 'metric', 'forecast_date', 'direction')},
            },
        ),
    ]
