# Generated by Django 5.2.8 on 2026-02-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0002_trendalert'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trendalert',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trendalert',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trendalert',
            name='related_crop_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trendalert',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('NOTIFIED', 'Notified')], default='NEW', max_length=10),
        ),
        migrations.RemoveField(
            model_name='trendalert',
            name='crop_id',
        ),
        migrations.RemoveField(
            model_name='trendalert',
            name='model_version',
        ),
    ]
