# Generated by Django 5.2.8 on 2026-02-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0003_alter_trendalert_unique_together_trendalert_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendalert',
            name='related_crop_id',
        ),
    ]
